# algo 
algo: "TQC"
total_timesteps: 1000000
algo_config:
    tensorboard_log: "../../../logs"
    policy: 'MlpPolicy'
    learning_rate: 0.00007
    learning_starts: 10000
    batch_size: 512
    use_sde: True

# env
env_id: "gcnm"
config: {}
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents"

# misc
id: "1"
additional_imports: []