# algo 
algo: "TQC"
total_timesteps: 1000000

# my config
# algo_config:
#     tensorboard_log: "../../../logs"
#     policy: 'MlpPolicy'
#     learning_rate: 0.0001
#     learning_starts: 100000
#     batch_size: 256
#     use_sde: True
#     buffer_size: 100000

# bipedal walker config
id: "bipedal-plus50"
algo_config:
    tensorboard_log: "../../../logs"
    policy: 'MlpPolicy'
    learning_rate: !!float 7.3e-4
    buffer_size: 300000
    batch_size: 256
    ent_coef: 'auto'
    gamma: 0.98
    tau: 0.02
    train_freq: 64
    gradient_steps: 64
    learning_starts: 10000
    use_sde: True
    policy_kwargs: "dict(log_std_init=-3, net_arch=[400, 300, 50])"

# env
env_id: "gcnm"
config: {}
n_envs: 12

# io
repo: "cboettig/rl-ecology"
save_path: "../saved_agents"

# misc
additional_imports: ["torch"]